version: '3.8'
name: microservice-demo-service

services:
  api-gateway:
    container_name: microservice-demo-api-gateway
    image: microservice-demo-api-gateway
    environment:
      - OCELOT_SERVICE_DISCOVERY_HOST=microservice-demo-consul
      - ASPNETCORE_HTTP_PORTS=5678
      - ASPNETCORE_ENVIRONMENT=Docker
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "5678:5678"
    build:
      context: .
      dockerfile: ./MicroserviceDemo.APIGateway/Dockerfile
    networks:
      - microservice-demo-network
      
  load-balancer:
    container_name: microservice-demo-load-balancer
    image: microservice-demo-load-balancer
    environment:
      - ASPNETCORE_HTTP_PORTS=5256
      - ASPNETCORE_ENVIRONMENT=Docker
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    expose:
      - "5256"
    ports:
      - "5256:5256"
    build:
      context: .
      dockerfile: ./MicroserviceDemo.LoadBalancer/Dockerfile
    networks:
      - microservice-demo-network
      
  identity-service:
    container_name: microservice-demo-identity-service
    image: microservice-demo-identity-service
    environment:
      - ASPNETCORE_HTTP_PORTS=5556
      - ASPNETCORE_ENVIRONMENT=Docker
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    expose:
      - "5556"
    ports:
      - "5556:5556"
    build:
      context: .
      dockerfile: ./MicroserviceDemo.IdentityService/Dockerfile
    networks:
      - microservice-demo-network
      
  microservice-demo-servicea:
    image: microservice-demo-servicea
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - ASPNETCORE_HTTP_PORTS=5029
      - ASPNETCORE_ENVIRONMENT=Docker
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    expose:
      - "5029"
    ports:
      - "5029"
    build:
      context: .
      dockerfile: ./MicroserviceDemo.ServiceA/Dockerfile
    networks:
      - microservice-demo-network
    depends_on:
      - load-balancer
      
  microservice-demo-serviceb:
    image: microservice-demo-serviceb
    deploy:
      mode: replicated
      replicas: 4
    environment:
      - SCHEMA_INSTANCE=https
      - ASPNETCORE_HTTP_PORTS=5267
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Admin1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    expose:
      - "5267"
    ports:
      - "5267"
    build:
      context: .
      dockerfile: ./MicroserviceDemo.ServiceB/Dockerfile
    networks:
      - microservice-demo-network
    volumes:
      - ~/.aspnet/https:/https:ro

networks:
  microservice-demo-network:
    external:
      name: microservice-demo-network