apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo-api-gateway
  labels:
    app: microservice-demo-api-gateway
spec:
  selector:
    matchLabels:
      app: microservice-demo-api-gateway
  template:
    metadata:
      labels:
        app: microservice-demo-api-gateway 
    spec:
      containers:
      - image: microservice-demo-api-gateway:latest #The Docker image for building the application container
        name: microservice-demo-api-gateway #The name of the application container
        imagePullPolicy: IfNotPresent
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Docker"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ASPNETCORE_HTTP_PORTS
            value: "5678"
          - name: HOST_PORT_INSTANCE
            value: "http://$(POD_IP):$(ASPNETCORE_HTTP_PORTS)"
          - name: OCELOT_SERVICE_DISCOVERY_HOST
            value: "microservice-demo-consul-service"
          - name: ConsulOptions__DiscoveryAddress
            value: "http://microservice-demo-consul-service:8500"
          - name: JwtOptions__Authority
            value: "http://microservice-demo-identity-service:5556"
          - name: JwtOptions__MetadataAddress
            value: "http://microservice-demo-identity-service:5556/.well-known/openid-configuration"
        ports:
          - containerPort: 5678 #The port for the application container

---
apiVersion: v1
kind: Service
metadata:
  name: microservice-demo-api-gateway-service
spec:
  selector:
    app: microservice-demo-api-gateway
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 5678
  type: NodePort