apiVersion: v1
kind: Service
metadata:
  name: microservice-demo-load-balancer-service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: microservice-demo-load-balancer
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 5256 #Service port
    targetPort: 5256 #The port for the application container