pipeline {

  agent any

  stages {

    stage('Checkout Source') {
      steps {
        git 'https://github.com/ms-hate-code/MicroserviceDemo.git'
      }
    }

    stage('Install Docker') {
      steps {
          sh '''
          apt-get update
          apt-get install ca-certificates curl
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
          chmod a+r /etc/apt/keyrings/docker.asc
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose

          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
            bookworm stable" | \
            tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt-get update

          apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          '''
      }
    }
    stage('Build image') {
      steps{
        sh '/usr/bin/docker-compose -f docker-compose.infrastructure.yml build'
        sh '/usr/bin/docker-compose -f docker-compose.service.yml build'
      }
    }

    stage('Pushing images to Dockerhub') {
      environment {
        registryCredential = 'dockerhub-credentials'
      }
      steps{
        script {
          def dockerImages = sh(script: 'docker images --format "{{.Repository}}:{{.Tag}}"', returnStdout: true).trim().split("\n")
          dockerImages.each { image ->
            docker.withRegistry( 'https://registry.hub.docker.com', registryCredential ) {
                sh "docker push ${image}"
            }
          }
        }
      }
    }

    stage('Deploying Microservice container to K8S') {
      steps {
        script {
          def deploymentFile = 'deployment.yml'
          def serviceFile = 'service.yml'
          def deploymentServices = ['api-gateway', 'identity-service', 'load-balancer', 'serviceA', 'serviceB']
          // Loop through the list and deploy each file
          for (service in deploymentServices) {
            kubernetesDeploy(configs: service + "/deployment.yaml", service + "/service.yaml")
          }
        }
      }
    }

  }

}