apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo-rabbitmq
  labels:
    app: microservice-demo-rabbitmq
spec:
  selector:
    matchLabels:
      app: microservice-demo-rabbitmq
  template:
    metadata:
      labels:
        app: microservice-demo-rabbitmq 
    spec:
      containers:
      - image: rabbitmq:3-management #The Docker image for building the application container
        name: microservice-demo-rabbitmq #The name of the application container
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5672 #The port for the application container
          - containerPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: microservice-demo-rabbitmq-service
spec:
  selector:
    app: microservice-demo-rabbitmq
  ports:
    - protocol: TCP
      name: "port1"
      port: 5672
      targetPort: 5672
    - protocol: TCP
      name: "port2"
      port: 15672
      targetPort: 15672