apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-demo-consul
  labels:
    app: microservice-demo-consul
spec:
  selector:
    matchLabels:
      app: microservice-demo-consul
  template:
    metadata:
      labels:
        app: microservice-demo-consul 
    spec:
      containers:
      - image: hashicorp/consul #The Docker image for building the application container
        name: microservice-demo-consul #The name of the application container
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8500 #The port for the application container

---
apiVersion: v1
kind: Service
metadata:
  name: microservice-demo-consul-service
spec:
  selector:
    app: microservice-demo-consul
  type: NodePort
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 8500
      nodePort: 30036